# docker-compose script to build code-server dev environment.
#
# Author : NoUnique (kofmap@gmail.com)
# Copyright 2020 NoUnique. All Rights Reserved

version: '2.2'

services:
  dev:
    image: anjia0532/wakeonlan:v1.0
    container_name: wakeonlan
    volumes:
      - ../secrets/wakeup-cache:/opt/wakeup/wakeup-cache
      - ../static/index.html:/opt/wakeup/static/index.html
      - ../static/app.js:/opt/wakeup/static/app.js
    restart: unless-stopped
    network_mode: host
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_IMAGE_NAME}.rule=PathPrefix(`/${COMPOSE_IMAGE_NAME}`)
      - traefik.http.services.${COMPOSE_IMAGE_NAME}.loadbalancer.server.port=9999
      - traefik.http.routers.${COMPOSE_IMAGE_NAME}.middlewares=${COMPOSE_IMAGE_NAME}-redirect,${COMPOSE_IMAGE_NAME}-strip
      - traefik.http.middlewares.${COMPOSE_IMAGE_NAME}-strip.stripprefix.prefixes=/${COMPOSE_IMAGE_NAME}
      - traefik.http.middlewares.${COMPOSE_IMAGE_NAME}-redirect.redirectregex.regex=^(?:.*:\/\/)?([^:\/]*?\.[^\/]*).*\/${COMPOSE_IMAGE_NAME}$$
      - traefik.http.middlewares.${COMPOSE_IMAGE_NAME}-redirect.redirectregex.replacement=https://$${1}/${COMPOSE_IMAGE_NAME}/
      - traefik.http.middlewares.${COMPOSE_IMAGE_NAME}-redirect.redirectregex.permanent=true
    entrypoint: /opt/wakeup/wakeup -s /opt/wakeup/static -c /opt/wakeup/wakeup-cache -l 0.0.0.0:9999

